os: linux
dist: trusty
language: php
php:
- 7.2
- 7.3
- 7.4
install: skip

script: skip
notifications:
  email: false
before_deploy:
  - wget https://github.com/boxbilling/boxbilling/releases/latest/download/BoxBilling.zip 
  - unzip ./BoxBilling.zip -d boxbilling
  - cp -r ./src/bb-config-heroku.php ./boxbilling/bb-config.php
  - cp -r ./boxbilling/htaccess.txt ./boxbilling/.htaccess
  - cp -r ./bin/prepare.php ./boxbilling/prepare.php
  - cp -r ./composer.json ./boxbilling/composer.json
  - cp -r ./composer.lock ./boxbilling/composer.lock
  - cp -r ./Procfile ./boxbilling/Procfile
  - rm -rf ./boxbilling/install
  - rm -rf ./boxbilling/htaccess.txt
  - rm -rf ./boxbilling/bb-config-sample.php
  - rm -rf BoxBilling.zip
  - cd boxbilling
deploy:
  provider: heroku
  api_key:
    secure: XbE/MMK6VAoKbyTgx200WOHxMOxjw8gc+PXsm3A9BNjGNnFrIqkOzedxLF+Jj6KwK6GDno4/8BNzoSO2FUm7R6dmRqfFGoVDMVtRz5hhcHsvGVJDd25zsyTTX5Sq62mn8TtvAFQK13W7+EK8pWQJ0ZVXEipiCUO2B8exkn+l/XowHC/pRZrWbbkFIeF+yqtMHXv4arlMam9907PBEud34fRtD27MZxkH3lyOtJ5/Qs/pNQVUk6h3EZK5Slm3jbLaPJhDcdZQze95AfiXjlfmvQyVvsFeGEOpu52JsJrTctDx6VLc/095ZIF6zBrXm6i3FGGu/PaGzhvoJz8doiskLTHBfvmRUX1FYsqvz1GeOmBnqiROULOD+Y3pJ1GLWOTaUMGqUDUD+IQQSEFcRodJV4JZCDvVdbxwJ8e/Fdl8F03tnCB5GBfxP+SMeFIarHATaFFZEvDvdlKOlkiLlEIgwrmL0uuXPnOCARb6B+i5ULE08pmUnMe6axOuiRnKXhANdmAn1h3JcG6qYq+b733sWeQS37/KQ/43D47miOc5lW4DwSnFfpMkIFFR5jHqpTk8dqHQhVw1ldyvW2ujAnsgchVHYscu498ZGkr+tPZKt7d5kRej3SsmnJlRdzkb7UmqqXIyPyLS8DzghcpdklP/OCxKnFnURzoJPCScvB9ZGSQ=
  app: boxbilling-demo
  skip_cleanup: true
  on:
    branch: dev/heroku
  run:
  - php prepare.php

after_deploy:
  - cd ../  