os: linux
dist: trusty
language: php
php:
- 7.4
install: skip
script: skip
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials  
- chmod +x bin/update_branch.sh
notifications:
  email: false
before_deploy:
- ./bin/update_branch.sh
- cp -r ./src/bb-config-heroku.php ./src/bb-config.php
- cp -r ./src/htaccess.txt ./src/.htaccess
- cp -r ./bin/prepare.php ./src/prepare.php
- cp -r ./Procfile ./src/Procfile
- rm -rf ./src/install
- rm -rf ./src/htaccess.txt
- rm -rf ./src/bb-config-sample.php
- cd src
deploy:
  provider: heroku
  api_key:
    secure: XbE/MMK6VAoKbyTgx200WOHxMOxjw8gc+PXsm3A9BNjGNnFrIqkOzedxLF+Jj6KwK6GDno4/8BNzoSO2FUm7R6dmRqfFGoVDMVtRz5hhcHsvGVJDd25zsyTTX5Sq62mn8TtvAFQK13W7+EK8pWQJ0ZVXEipiCUO2B8exkn+l/XowHC/pRZrWbbkFIeF+yqtMHXv4arlMam9907PBEud34fRtD27MZxkH3lyOtJ5/Qs/pNQVUk6h3EZK5Slm3jbLaPJhDcdZQze95AfiXjlfmvQyVvsFeGEOpu52JsJrTctDx6VLc/095ZIF6zBrXm6i3FGGu/PaGzhvoJz8doiskLTHBfvmRUX1FYsqvz1GeOmBnqiROULOD+Y3pJ1GLWOTaUMGqUDUD+IQQSEFcRodJV4JZCDvVdbxwJ8e/Fdl8F03tnCB5GBfxP+SMeFIarHATaFFZEvDvdlKOlkiLlEIgwrmL0uuXPnOCARb6B+i5ULE08pmUnMe6axOuiRnKXhANdmAn1h3JcG6qYq+b733sWeQS37/KQ/43D47miOc5lW4DwSnFfpMkIFFR5jHqpTk8dqHQhVw1ldyvW2ujAnsgchVHYscu498ZGkr+tPZKt7d5kRej3SsmnJlRdzkb7UmqqXIyPyLS8DzghcpdklP/OCxKnFnURzoJPCScvB9ZGSQ=
  app: boxbilling-demo
  skip_cleanup: true
  on:
    branch: dev/heroku
  run:
  - php prepare.php
after_deploy:
- cd ../
env:
  global:
    secure: tVzZ+3U0ndBGvoUpFqA6ikg6fDKnPgMoNqK1pvTdEp0xmrFtjMP/fuc8+awObhj89iEC+MyzfsOP57CZbHR/UjmUSHPQew+BvTwxYmTUzgUeyUrYsTEI7WJgB7tsL35aRgrpxk102tlSmlX7EonufUT0svPOAQ1p4NgZRm3GI3A=
